import Link from "next/link";
import Head from "next/head";

export default function Header() {
  return (
    <>
      <Head>
        <title>PHOTO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-full"></div>

      <header className="fixed top-0 w-full z-20 flex justify-between items-center h-[70px] px-10 bg-stone-900">
        <span className="uppercase text-md font-medium text-white ">
          Photography Portfolio
        </span>

        <Link
          href="/contact"
          className="rounded-3xl bg-white text-stone-700 px-3 py-2 hover:bg-opacity-90"
        >
          Get in touch
        </Link>
      </header>
    </>
  );
}
