import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Link from "next/link";


// import styles
import "lightgallery/css/lightgallery.css";
import "lightgallery/css/lg-zoom.css";
import "lightgallery/css/lg-thumbnail.css";




export default function Home() {
  return (
    <div className=" h-full bg-[url('../public/bgIMG.jpg')] bg-fixed bg-center bg-cover overflow-auto ">
      <Head>
        <title>CONTACT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="overflow-auto fixed top-0 w-full z-20 flex justify-between items-center h-[70px] px-10 bg-stone-900">
        <span className="uppercase text-md font-medium ">
          Photography Portfolio
        </span>

        <Link
          href="#"
          className="rounded-3xl bg-white text-stone-700 px-3 py-2 hover:bg-opacity-90 overflow-auto"
        >
          Get in touch
        </Link>
      </header>

      <main className="h-full pt-[110px]">
        <div className="">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sed
          consectetur lacus. Cras ac lacus pellentesque, porta diam sed,
          dignissim purus. Curabitur velit leo, porta eget suscipit ut, congue
          in ligula. Aenean condimentum a eros in varius. Ut non mi a massa
          tincidunt sagittis non nec ipsum. Donec elit nunc, scelerisque quis
          vestibulum ut, rhoncus et magna. Quisque blandit finibus dictum.
          Aliquam facilisis tempus tellus, eu varius lorem auctor ac.
          Suspendisse sapien arcu, dapibus vel eros interdum, tempor congue
          erat. Morbi facilisis purus vel nisi molestie ultrices. Vivamus
          tincidunt ornare elit euismod congue. Phasellus eget tortor suscipit,
          scelerisque ex eu, egestas quam. Integer augue eros, aliquam a nulla
          ac, porta commodo felis.
        </div>
      </main>

      <footer className="fixed bottom-0 w-full z-20  h-[90px] bg-stone-900 flex justify-center items-center uppercase text-lg font-medium">
        <p> FOOTER PLACEHOLDER </p>
      </footer>
    </div>
  );
}
