import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import { Tab } from '@headlessui/react'
import Masonry from 'react-masonry-css'
import classNames from 'classnames'


const inter = Inter({ subsets: ['latin'] })
const tabs = [
  {
    key:'All', 
    display: 'All'},
    {
      key:'Luis',
      display:'Luisccam'
  },
  {
    key:'Sean',
    display:'Loftyy'

  }
]

export default function Home() {
  return (
    <div className=" h-full bg-[url('/photo-bg.jpg')] bg-center bg-cover overflow-auto ">
      <Head>
        <title>PHOTO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="fixed top-0 w-full z-10 flex justify-between items-center h-[80px] px-10 bg-stone-900"> 
        <span className="uppercase text-lg font-medium ">Photography Portfolio</span>

        <Link href="#" className="rounded-3xl bg-white text-stone-700 px-3 py-2 hover:bg-opacity-90">
          Get in touch
        </Link>
      
      </header>
      
      <main className="pt-[110px]">
        <div className="flex flex-col items-center h-full">

        <Tab.Group>
      <Tab.List className="flex items-center gap-12 ">


         {tabs.map(tab => (
          <Tab key={tab.key} className="p-2">
          {({selected}) =>(
          <span className={classNames("uppercase", selected ? 'text-white': 'text-stone-600')}>
            {tab.display}
          </span>
          )}
        </Tab>
         ))}
        
        
      </Tab.List>
      <Tab.Panels className="h-full bg-stone-900 bg-opacity-80 h-full max-w-[900px] w-full p-2 sm:p-4 my-6">
        
        <Tab.Panel>
          <Masonry 
            breakpointCols={2}
            className="flex gap-4"
            columnClassName="">
            <img src="/photos/tormented.jpg" alt="tormented" className="my-4"/>
            <img src="/photos/medusa.jpg" alt="medusa" className="my-4"/>
            <img src="/photos/Foggy Night -01.jpg" alt="fog1" className="my-4"/>
            <img src="/photos/Foggy Night -02.jpg" alt="fog2" className="my-4"/>
            <img src="/photos/Foggy Night -03.jpg" alt="fog3" className="my-4"/>
          </Masonry>
        </Tab.Panel>


        <Tab.Panel>Luisccam</Tab.Panel>
        <Tab.Panel>Loftyy</Tab.Panel>
      </Tab.Panels>
    </Tab.Group>    

        </div>
      

      </main>

      <footer className="h-[90px] flex justify-center items-center uppercase text-lg font-medium">
        
       <p> FOOTER PLACEHOLDER </p>

      </footer>
    </div>
  )
}
